# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables: {System.Debug: true}

trigger:
- master

stages:
  - stage: boot
    displayName: "Bootstrap"
    jobs:
      - job: Linux
        pool:
          vmImage: 'ubuntu-latest'
        variables:
          group: linux
        steps:
        - script: echo "owobjdir=$(owobjdir)"
        - bash: azure/build.sh
          displayName: "Bootstrap"
          env: {OWAZURE_STAGE_NAME: boot, OWOBJDIR: $(owobjdir), OWTOOLS: GCC, OWDEBUG: $(owdebug)}
        - task: PublishPipelineArtifact@1
          displayName: "Save Cache"
          inputs: {artifactName: $(owobjdir), targetPath: build/$(owobjdir)}
      - job: Windows
        pool:
          vmImage: 'vs2017-win2016'
        variables:
          group: windows
        steps:
        - script: echo "owobjdir=$(owobjdir)"
        - script: azure/build.cmd
          displayName: "Bootstrap"
          env: {OWAZURE_STAGE_NAME: boot, OWDEBUG: $(owdebug)}
        - task: PublishPipelineArtifact@1
          displayName: "Save Cache"
          inputs: {artifactName: $(owobjdir), targetPath: build/$(owobjdir)}
      - job: OSX
        pool:
          vmImage: 'macOS-latest'
        steps:
        - script: echo "owobjdir=$(owobjdir)"
        - bash: azure/build.sh
          displayName: "Bootstrap"
          env: {OWAZURE_STAGE_NAME: boot, OWOBJDIR: $(owobjdir), OWTOOLS: CLANG, OWDEBUG: $(owdebug)}
        - task: PublishPipelineArtifact@1
          displayName: "Save Cache"
          inputs: {artifactName: $(owobjdir), targetPath: build/$(owobjdir)}
  - stage: build
    displayName: "Build"
    jobs:
      - job: Linux
        pool:
          vmImage: 'ubuntu-latest'
        variables:
          group: linux
        steps:
        - task: DownloadPipelineArtifact@2
          displayName: "Load Cache"
          inputs: {buildType: 'current', artifactName: $(owobjdir), targetPath: build/$(owobjdir)}
        - bash: azure/build.sh
          displayName: "Build"
          env: {OWAZURE_STAGE_NAME: build, OWOBJDIR: $(owobjdir), OWTOOLS: GCC, OWDEBUG: $(owdebug)}
      - job: Windows
        timeoutInMinutes: 120
        pool:
          vmImage: 'vs2017-win2016'
        variables:
          group: windows
        steps:
        - task: DownloadPipelineArtifact@2
          displayName: "Load Cache"
          inputs: {buildType: 'current', artifactName: $(owobjdir), targetPath: build/$(owobjdir)}
        - script: azure/build.cmd
          displayName: "Build"
          env: {OWAZURE_STAGE_NAME: build, OWDEBUG: $(owdebug)}
      - job: OSX
        timeoutInMinutes: 120
        pool:
          vmImage: 'macOS-latest'
        steps:
        - task: DownloadPipelineArtifact@2
          displayName: "Load Cache"
          inputs: {buildType: 'current', artifactName: $(owobjdir), targetPath: build/$(owobjdir)}
        - bash: azure/build.sh
          displayName: "Build"
          env: {OWAZURE_STAGE_NAME: build, OWOBJDIR: $(owobjdir), OWTOOLS: CLANG, OWDEBUG: $(owdebug)}
  - stage: update
    displayName: "Update Build"
    jobs:
      - job: Linux
        pool:
          vmImage: 'ubuntu-latest'
        variables:
          group: linux
        steps:
        - task: DownloadPipelineArtifact@2
          displayName: "Load Cache"
          inputs: {buildType: 'current', artifactName: $(owobjdir), targetPath: build/$(owobjdir)}
      - job: Windows
        pool:
          vmImage: 'vs2017-win2016'
        variables:
          group: windows
        steps:
        - task: DownloadPipelineArtifact@2
          displayName: "Load Cache"
          inputs: {buildType: 'current', artifactName: $(owobjdir), targetPath: build/$(owobjdir)}
  - stage: tests
    displayName: "Tests"
    jobs:
      - job: Linux
        pool:
          vmImage: 'ubuntu-latest'
        variables:
          group: linux
      - job: Windows
        pool:
          vmImage: 'vs2017-win2016'
        variables:
          group: windows
  - stage: docs
    displayName: "Documentation Build"
    jobs:
      - job: Windows
        timeoutInMinutes: 120
        pool:
          vmImage: 'vs2017-win2016'
        variables:
          group: windows
  - stage: instal
    displayName: "Build Installers"
    jobs:
      - job: Linux
        pool:
          vmImage: 'ubuntu-latest'
        variables:
          group: linux
        steps:
        - task: DownloadPipelineArtifact@2
          displayName: "Load Cache"
          inputs: {buildType: 'current', artifactName: $(owobjdir), targetPath: build/$(owobjdir)}
      - job: Windows
        pool:
          vmImage: 'vs2017-win2016'
        variables:
          group: windows
        steps:
        - task: DownloadPipelineArtifact@2
          displayName: "Load Cache"
          inputs: {buildType: 'current', artifactName: $(owobjdir), targetPath: build/$(owobjdir)}
  - stage: release
    displayName: "Make Release on GitHub"
    jobs:
      - job: Linux
        pool:
          vmImage: 'ubuntu-latest'
        variables:
          group: linux
