# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables: {System.Debug: true}

jobs:
- job: "All_in_one"
  pool:
    vmImage: 'vs2017-win2016'
  variables:
    owtools: VISUALC
    owazure_debug: 1
  steps:
    - script: azure\build.cmd
      displayName: Bootstrap
      env: {OWAZURE_STAGE_NAME: Bootstrap}
    - script: azure\build.cmd
      displayName: "Build"
      env: {OWAZURE_STAGE_NAME: Build}
    - script: azure\build.cmd
      displayName: "Update Build"
      env: {OWAZURE_STAGE_NAME: Update Build}
    - script: azure\build.cmd
      displayName: "Tests"
      env: {OWAZURE_STAGE_NAME: Tests}
    - script: azure\build.cmd
      displayName: "Documentation"
      env: {OWAZURE_STAGE_NAME: Documentation}
    - script: azure\build.cmd
      displayName: "Release"
      env: {OWAZURE_STAGE_NAME: Release}
    - script: set
