# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables: {System.Debug: true}

jobs:
- job: "All_in_one"
  pool:
    vmImage: 'vs2017-win2016'
  variables:
    owtools: VISUALC
    owazure_debug: 1
  steps:
    - script: azure\build.cmd
      displayName: Bootstrap
      env: {OWAZURE_STAGE_NAME: Bootstrap}
    - script: azure\build.cmd
      displayName: "Build"
      env: {OWAZURE_STAGE_NAME: Build}
    - script: azure\build.cmd
      displayName: "Update Build"
      env: {OWAZURE_STAGE_NAME: Update Build}
    - script: azure\build.cmd
      displayName: "Test wasm assembler"
      env: {OWAZURE_STAGE_NAME: Tests,
            OWTOOLS: WATCOM,
            OWAZURETEST: WASM}
    - script: azure\build.cmd
      displayName: "Test C compiler"
      env: {OWAZURE_STAGE_NAME: Tests,
            OWTOOLS: WATCOM,
            OWAZURETEST: C}
    - script: azure\build.cmd
      displayName: "Test FORTRAN 77 compiler"
      env: {OWAZURE_STAGE_NAME: Tests,
            OWTOOLS: WATCOM,
            OWAZURETEST: F77}
    - script: azure\build.cmd
      displayName: "Test C++ compiler"
      env: {OWAZURE_STAGE_NAME: Tests,
            OWTOOLS: WATCOM,
            OWAZURETEST: CXX}
    - script: azure\build.cmd
      displayName: "Test C run-time library"
      env: {OWAZURE_STAGE_NAME: Tests,
            OWTOOLS: WATCOM,
            OWAZURETEST: CRTL}
    - script: azure\build.cmd
      displayName: "Documentation"
      env: {OWAZURE_STAGE_NAME: Documentation}
    - script: azure\build.cmd
      displayName: "Release"
      env: {OWAZURE_STAGE_NAME: Release}
