# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables: {System.Debug: true, owdebug: 1}

schedules:
- cron: "0 1 * * *"
  displayName: Daily build
  branches:
    include:
    - master

trigger:
- master

stages:
  - stage: boot
    displayName: "Bootstrap"
    jobs:
      - job: Linux
        pool:
          vmImage: 'ubuntu-latest'
        variables:
          owobjdir: binlnx
        steps:
        - script: azure/buildx.sh
          displayName: "Bootstrap"
          env: {OWAZURE_STAGE_NAME: boot, OWOBJDIR: $(owobjdir), OWTOOLS: GCC, OWDEBUG: $(owdebug)}
        - template: azure/artifsav.yml
      - job: Windows
        pool:
          vmImage: 'vs2017-win2016'
        variables:
          owobjdir: binnt
        steps:
        - script: azure/buildx.cmd
          displayName: "Bootstrap"
          env: {OWAZURE_STAGE_NAME: boot, OWOBJDIR: $(owobjdir), OWTOOLS: VISUALC, OWDEBUG: $(owdebug)}
        - template: azure/artifsav.yml
      - job: OSX
        pool:
          vmImage: 'macOS-latest'
        variables:
          owobjdir: binosx
        steps:
        - script: azure/buildx.sh
          displayName: "Bootstrap"
          env: {OWAZURE_STAGE_NAME: boot, OWOBJDIR: $(owobjdir), OWTOOLS: CLANG, OWDEBUG: $(owdebug)}
        - template: azure/artifsav.yml
  - stage: build
    displayName: "Build"
    jobs:
      - job: Linux
        pool:
          vmImage: 'ubuntu-latest'
        variables:
          owobjdir: binlnx
        steps:
        - template: azure/artiflod.yml
        - script: sudo apt-get install -y dosbox
        - script: azure/buildx.sh
          displayName: "Build"
          env: {OWAZURE_STAGE_NAME: build, OWOBJDIR: $(owobjdir), OWTOOLS: GCC, OWDEBUG: $(owdebug), OWDOSBOX: dosbox, SDL_VIDEODRIVER: dummy}
        - template: azure/relsave.yml
      - job: Windows
        timeoutInMinutes: 120
        pool:
          vmImage: 'vs2017-win2016'
        variables:
          owobjdir: binnt
        steps:
        - template: azure/artiflod.yml
        - script: azure/buildx.cmd
          displayName: "Build"
          env: {OWAZURE_STAGE_NAME: build, OWOBJDIR: $(owobjdir), OWTOOLS: VISUALC, OWDEBUG: $(owdebug)}
        - template: azure/relsave.yml
      - job: OSX
        timeoutInMinutes: 120
        pool:
          vmImage: 'macOS-latest'
        variables:
          owobjdir: binosx
        steps:
        - template: azure/artiflod.yml
        - script: brew install dosbox
        - script: azure/buildx.sh
          displayName: "Build"
          env: {OWAZURE_STAGE_NAME: build, OWOBJDIR: $(owobjdir), OWTOOLS: CLANG, OWDEBUG: $(owdebug), OWDOSBOX: dosbox, SDL_VIDEODRIVER: dummy}
  - stage: update
    displayName: "Update Build"
    jobs:
      - job: Linux
        pool:
          vmImage: 'ubuntu-latest'
        variables:
          owobjdir: binlnx
        steps:
        - template: azure/artiflod.yml
        - template: azure/relload.yml
  - stage: tests
    displayName: "Tests"
    jobs:
      - job: Linux
        pool:
          vmImage: 'ubuntu-latest'
        variables:
          owobjdir: binlnx
      - job: Windows
        pool:
          vmImage: 'vs2017-win2016'
        variables:
          owobjdir: binnt
  - stage: docs
    displayName: "Documentation Build"
    jobs:
      - job: Windows
        timeoutInMinutes: 120
        pool:
          vmImage: 'vs2017-win2016'
        variables:
          owobjdir: binnt
        steps:
        - script: azure/buildx.cmd
          displayName: "Documentation Build"
          env: {OWAZURE_STAGE_NAME: docs, OWOBJDIR: $(owobjdir), OWTOOLS: VISUALC, OWDEBUG: $(owdebug)}
  - stage: instal
    displayName: "Build Installers"
    jobs:
      - job: Linux
        pool:
          vmImage: 'ubuntu-latest'
        variables:
          owobjdir: binlnx
        steps:
        - template: azure/artiflod.yml
        - script: azure/buildx.sh
          displayName: "Build Installers"
          env: {OWAZURE_STAGE_NAME: inst, OWOBJDIR: $(owobjdir), OWTOOLS: VISUALC, OWDEBUG: $(owdebug)}
      - job: Windows
        pool:
          vmImage: 'vs2017-win2016'
        variables:
          owobjdir: binnt
        steps:
        - template: azure/artiflod.yml
        - script: azure/buildx.cmd
          displayName: "Build Installers"
          env: {OWAZURE_STAGE_NAME: inst, OWOBJDIR: $(owobjdir), OWTOOLS: VISUALC, OWDEBUG: $(owdebug)}
  - stage: release
    displayName: "Make Release on GitHub"
    jobs:
      - job: Linux
        pool:
          vmImage: 'ubuntu-latest'
        variables:
          owobjdir: binlnx
