# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: "All_in_one"
  pool:
    vmImage: 'vs2017-win2016'
  variables:
    owazuredir: $env:OWROOT\azure
    owtools: VISUALC
  steps:
    - script: $(owazuredir)\build.cmd
      displayName: Bootstrap
      env: {OWSTAGE_NAME: Bootstrap}
    - script: $(owazuredir)\build.cmd
      displayName: "Build"
      env: {OWSTAGE_NAME: Build}
    - script: $(owazuredir)\build.cmd
      displayName: "Update Build"
      env: {OWSTAGE_NAME: Update Build}
    - script: $(owazuredir)\build.cmd
      displayName: "Tests"
      env: {OWSTAGE_NAME: Tests}
    - script: $(owazuredir)\build.cmd
      displayName: "Documentation"
      env: {OWSTAGE_NAME: Documentation}
    - script: $(owazuredir)\build.cmd
      displayName: "Release"
      env: {OWSTAGE_NAME: Release}
    - script: set
