# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables: {System.Debug: true, owazure_debug: 1}

stages:
  - stage: boot
    displayName: "Bootstrap"
    jobs:
      - job: Linux
        pool:
          vmImage: 'ubuntu-latest'
      - job: Windows
        pool:
          vmImage: 'vs2017-win2016'
      - job: OSX
        pool:
          vmImage: 'macOS-latest'
  - stage: build
    displayName: "Build"
    jobs:
      - job: Linux
        pool:
          vmImage: 'ubuntu-latest'
      - job: Windows
        timeoutInMinutes: 120
        pool:
          vmImage: 'vs2017-win2016'
      - job: OSX
        timeoutInMinutes: 120
        pool:
          vmImage: 'macOS-latest'
  - stage: update
    displayName: "Update Build"
    jobs:
      - job: Linux
        pool:
          vmImage: 'ubuntu-latest'
      - job: Windows
        pool:
          vmImage: 'vs2017-win2016'
  - stage: tests
    displayName: "Tests"
    jobs:
      - job: Linux
        pool:
          vmImage: 'ubuntu-latest'
      - job: Windows
        pool:
          vmImage: 'vs2017-win2016'
  - stage: docs
    displayName: "Documentation Build"
    jobs:
      - job: Windows
        timeoutInMinutes: 120
        pool:
          vmImage: 'vs2017-win2016'
  - stage: instal
    displayName: "Build Installers"
    jobs:
      - job: Linux
        pool:
          vmImage: 'ubuntu-latest'
      - job: Windows
        pool:
          vmImage: 'vs2017-win2016'
  - stage: release
    displayName: "Make Release on GitHub"
      - job: Linux
        pool:
          vmImage: 'ubuntu-latest'
