# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: "All_in_one"
  pool:
    vmImage: 'vs2017-win2016'
  steps:
    - script: echo Hello, world!
      displayName: Bootstrap
    - script: echo Add other tasks to build, test, and deploy your project.
      displayName: "Build"
    - script: echo Update Build!
      displayName: "Update Build"
    - script: echo Tests!
      displayName: "Tests"
    - script: echo Build Documentation!
      displayName: "Documentation"
    - script: echo Build 64-bit Windows installer!
      displayName: "Release"
    - script: set
