# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: "Bootstrap"
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: echo Hello, world!

- job: "Build"
  dependsOn: "Bootstrap"
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: echo Add other tasks to build, test, and deploy your project.

- job: "Update_Build"
  dependsOn: "Build"
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: echo Update Build!

- job: "Tests"
  dependsOn: "Update_Build"
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: echo Tests!

- job: "Documentation"
  dependsOn: "Tests"
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: echo Build Documentation!

- job: "Release"
  dependsOn: "Documentation"
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: echo Build 64-bit Windows installer!

